baseURL: https://dothidden.xyz/
languageCode: en-us
title: .hidden
buildDrafts: true
copyright: .hidden

params: 
  description: Adventures following the white rabbit
  mode: toggle
  social: 
    - name: GitHub
      icon: github
      url: https://github.com/orgs/dothidden/repositories
    - name: CTFtime
      icon: codesandbox
      url: https://ctftime.org/team/225182
    - name: RSS
      icon: rss
      url: https://dothidden.xyz/index.xml
  excludedSections:
    - about
  homeWriteupCnt: 10
  #mathjax: true
  katex: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: About
      url: /about
      weight: 3
