baseURL: https://dothidden.xyz/
languageCode: en-us
title: .hidden
buildDrafts: true
copyright: .hidden
titleCaseStyle: none

params:
  description: Adventures following the white rabbit...
  mode: toggle
  social:
    - name: GitHub
      icon: github
      url: https://github.com/orgs/dothidden/repositories
    - name: CTFtime
      icon: codesandbox
      url: https://ctftime.org/team/225182
    - name: RSS
      icon: rss
      url: https://dothidden.xyz/index.xml
  members:
    - name: sunbather
      link: https://github.com/costinteo
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: [ 'pwn','rev','crypto' ]
      description:
        - bash wizard
        - video game enjoyer
    - name: zenbassi
      link: https://github.com/stefan-radu
      picture: https://avatars.githubusercontent.com/u/30214214?v=4
      tags: [ 'rev', 'pwn', 'misc' ]
      description:
        - likes vim a bit too much
        - into (film) photography
    - name: Koyossu
      link: https://github.com/SecioreanuStefanita
      picture: https://avatars.githubusercontent.com/u/48451382?s=400&u=b2a10a33c3ec8062c8b99e9191ee85af061272ef&v=4
      tags: [ 'web','misc','forensics','mobile' ]
      description:
        - Backend Bandit & De-bug Demon
        - Do not do it...
        - d293ISB5b3UgcmVhbGx5IGRlY29kZWQgdGhpcyA=
    - name: H0N3YP0T
      link: https://github.com/Mathis-Dory
      picture: https://ctftime.org/media/cache/52/af/52af19f614f045a44bcd409964613ac4.jpg
      tags: [ 'osint','forensics','web','misc','network' ]
      description:
        - I will find you, I'm really gonna find you...
        - The only Belgian of the team
        - FLAG{5TAY_CUR10U5_AND_CUNN1NG}
    - name: MettleSphee
      link: https://github.com/MettleSphee
      picture: https://avatars.githubusercontent.com/u/69507856?s=400&u=6b8b52fb7d3634193be75ee1e60bd87457fd29e4&v=4
      tags: [ 'osint','forensics','crypto','misc','mobile' ]
      description:
        - Don't let a bug ruin your amazing experience. Exploit it!
    - name: cartouche70
      link: https://github.com/DalmatianuSebikk
      picture: https://avatars.githubusercontent.com/u/70603934?v=4
      tags: ['web','forensics','crypto','misc']
      description:
        - keeps injecting malicious code
        - games and sports enjoyer.
    - name: expnx
      link: https://github.com/bogdan-stelea
      picture: https://avatars.githubusercontent.com/u/57039482?s=400&u=1544a8a3b9e76f644cdcfaf28e52c9cd0238f226&v=4
      tags: ['web', 'pwn' ,'misc']
      description:
        - I don't know what I am doing
    - name: Honesty
      link: https://github.com/MxHonesty
      picture: https://avatars.githubusercontent.com/u/11357963?v=4
      tags: [ 'rev', 'pwn', 'network' ]
      description:
        - currently unwinding the stack
    - name: PineBel
      link: https://github.com/Stefan2320
      picture: https://avatars.githubusercontent.com/u/77758442?s=400&u=66d9d227463285d74e23bcbedbdcb712555defa7&v=4
      tags: [ 'pwn', 'rev', 'misc' ]
      description:
        - Segmentation faults make me happy
        - The second Belgian
    - name: Hust
      link: https://github.com/radumihai8
      picture: https://avatars.githubusercontent.com/u/17956023?v=4
      tags: [ 'web', 'forensics', 'misc' ]
      description:
        - Exploring the depths of web security
    - name: GabrielMajeri
      link: https://github.com/GabrielMajeri
      picture: https://avatars.githubusercontent.com/u/3010346?v=4
      tags: [ 'crypto', 'network', 'web', 'rev', 'misc' ]
      description:
        - I like breaking stuff
  excludedSections:
    - about
    - events
  homeWriteupCnt: 10
  katex: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Events
      url: /events
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4

markup:
  goldmark:
    renderer:
      # To allow including raw HTML tags in our Markdown input
      unsafe: true
